# This is a basic workflow to help you get started with Actions

name: Update hats CI

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
           
      # Clone the repos that the hats updater is going to use
      - name: Clone repos 
        run: |
          rm -rf THE_OTHER_ROLES
          git clone https://github.com/Eisbison/TheOtherHats


      # Run updater  that copies the files & updates the json  
      - name: Run hats updater 
        run: |
          dotnet GITHUB_ACTIONS/HatsUpdater.dll
          
      # Remove all cloned repos  
      - name : Clean 
        run: | 
          rm -rf TheOtherHats

      # Push and commit 
      - name: Git commit & push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add . 
          git diff --quiet && git diff --staged --quiet || git commit -am 'Updated hats'
          git push
         
